## Window settings
version: "v0.1.1"
screenWidth: 1600
screenHeight: 900
maxTPS: 60 # how many times update is called, will game game speed at the moment

## Game settings
maxParticles: 0 #1440000 # 1600*900, set to 0 for recommended is screenWidth*screenHeight
rainAmount: 10 # how much rain spawns every frame. 0 turns rain off
showSkippedParticles: false

verboseLogging: true