##  [ DEV CONFIG ]  ##
## Window Settings
version: "v0.1.1"
maxTPS: 60
screenSize:
  X: 800
  Y: 600
backgroundColor:
  R: 30
  G: 30
  B: 30
  A: 255
particleColor: 
   R: 255
   G: 255
   B: 255
   A: 255
showSkippedParticles: false
skippedParticleColor:
  R: 255
  G: 120
  B: 120
  A: 255
verboseLogging: true
rainRate: 10