##  [ DEV CONFIG ]  ##
version: "v0.1.2"
# Gravity is borked atm
gravity: 1
verboseLogging: true

## Window settings
maxTPS: 60
screenSize:
  X: 1200
  Y: 720

## Game settings
rainRate: 1
backgroundColor:
  R: 30
  G: 30
  B: 30
  A: 255
particleColor: 
   R: 255
   G: 255
   B: 255
   A: 255
showSkippedParticles: true
skippedParticleColor:
  R: 255
  G: 160
  B: 160
  A: 255

## UI Settings
fontFilePath: "res/fonts/font2.ttf"
uiTextColor:
  R: 255
  G: 255
  B: 255
  A: 255