##  [ BUILD CONFIG ]  ##
version: "v0.1.1"
verboseLogging: true

## Window settings
maxTPS: 60
screenSize:
  X: 800
  Y: 600

## Game settings
backgroundColor:
  R: 30
  G: 30
  B: 30
  A: 255
particleColor: 
   R: 255
   G: 255
   B: 255
   A: 255
showSkippedParticles: false
skippedParticleColor:
  R: 255
  G: 120
  B: 120
  A: 255
rainRate: 1

## UI Settings
fontFilePath: "res/font.ttf"
uiTextColor:
  R: 255
  G: 255
  B: 255
  A: 255